# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c21e03ab-ce91-4b53-bb54-b0c9fdf6676d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9549-C1EE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/gamingDrive" =
    { device = "/dev/disk/by-uuid/1f88c0b6-0dff-4390-8a16-6c3d04bb333f";
      fsType = "ext4";
    };

  fileSystems."/mnt/bulkStorage" =
    { device = "/dev/disk/by-uuid/83f44b58-f326-49da-92a5-30758d590bd3";
      fsType = "ext4";
    };

  fileSystems."/mnt/backBurner" =
    { device = "/dev/disk/by-uuid/5f00153b-1543-471e-86e5-73ba4ebe7067";
      fsType = "ext4";
    };

  fileSystems."/mnt/1TBsdd" =
    { device = "/dev/disk/by-uuid/06e7cd38-9d4a-4e9c-89d6-25f0cfab5182";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
