{
  imports = [
    ./autoUpgrade.nix
    ./boot.nix
    ./env.nix
    ./hardware.nix
    ./home-manager.nix
    ./hyprland.nix
    ./mime.nix
    ./network.nix
    ./nh.nix
    ./nix.nix
    ./packages.nix
    ./security.nix
    ./services.nix
    ./timezone.nix
    ./user.nix
    ./zram.nix
  ];
}
